### ISSUE TITLE
Implementation of program output

### ISSUE THREAD

**Issue by turtlelazy** [hunter-classes/fall-2022-135-lab-07-natalie-gallo#2]
https://github.com/hunter-classes/fall-2022-135-lab-07-natalie-gallo/blob/847e3f3e6088adef4b8db44cf44e7a7bfc3691b7/main.cpp#L10

It may be useful to create a function that takes in a string parameter to in turn return the string in a prettified format. I believe that would allow for modular coding.

**Comment by natalie-gallo** [comment]
Good idea, go for it!
